manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
 #   - name: urob
 #     url-base: https://github.com/urob
    - name: mralex07
      url-base: https://github.com/mralex07
  projects:
    - name: zmk
      remote: mralex07
      revision: main
      import: app/west.yml
  self:
    path: config
